class UserModel {
  final String? id;          // MongoDB _id
  final String userId;       // auto-generated by backend
  final String name;
  final String mobile;
  final String role;
  final String password;
  final String createdAt;
  final String segment;

  UserModel({
    this.id,
    required this.userId,
    required this.name,
    required this.mobile,
    required this.role,
    required this.password,
    required this.createdAt,
    required this.segment,
  });

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['_id']?.toString(),
      userId: json['user_id']?.toString() ?? "",
      name: json['name'] ?? "",
      mobile: json['mobile'] ?? "",
      role: json['role'] ?? "",
      password: json['password'] ?? "",
      createdAt: json['created_at'] ?? "",
      segment: json['segment'] ?? "",
    );
  }

  // SEND ONLY WHAT BACKEND NEEDS FOR ADD USER
  Map<String, dynamic> toJson() {
  return {
    "name": name,
    "mobile": mobile,
    "role": role,
    "password": password,
    "segment": segment,
  };
}

}
